[model]
mode = tes
msp = cpt

[data]
ws = 100
ic = 55
oc = 55
ds = MSL
f_tr = 0.5
dr = 0.3
dp = dataset/MSL

[train]
lr = 0.001
c_list = [3, 5, 7]
gpu = 0
epoch = 8
ar = 4
bs = 256
seed = 1

[param]
d = 256
l = 2
